spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprisehub
spring.datasource.username=enterprisehub
spring.datasource.password=enterprisehub123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080